name: CI

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update

    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker \
          run --rm \
          dockcross/linux-armv7a > dockercross
        chmod +x dockercross
        ./dockercross bash -c "autoreconf -iv && ./configure --host=arm-linux-gnueabi && make"

    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Artifacts
        path: ./evtest

  pre-release:
    needs: build
    runs-on: [ ubuntu-latest ]
    if: "!startsWith(github.ref, 'refs/tags/v')"
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: Artifacts
        path: ./evtest

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          evtest

  release:
    needs: build
    runs-on: [ ubuntu-latest ]
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: Artifacts
        path: ./evtest

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          evtest
